export default [
  'name_barChartHorizontal',
  'name_heartOutline',
  'name_tagOutline',
  'name_calendar',
  'name_infoCircleOutline',
  'name_searchSmall',
  'name_folder',
  'name_copy',
  'name_notificationOutline',
  'name_table',
  'name_cloudOutline',
  'name_idCard',
  'name_pieChartOutline',
  'name_barChartAlt',
  'name_barChartSquare',
  'name_fileFind',
  'name_show',
  'name_mention',
  'name_user',
  'name_lineChartDown',
  'name_chatAlt',
  'name_terminal',
  'name_warningOutline',
  'name_addRow',
  'name_gridHorizontalRound rotate_270',
  'name_barBottom',
];
